# Generated by Django 6.0.6 on 2026-06-05 17:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_alter_subject_id'),
        ('students', '0002_remove_student_photo_alter_student_student_id'),
    ]

    operations = [
        migrations.AddIndex(
            model_name='student',
            index=models.Index(fields=['deleted_at'], name='students_st_deleted_257675_idx'),
        ),
    ]
