# Generated by Django 6.0.6 on 2026-06-05 18:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0003_alter_category_unique_together_and_more'),
        ('students', '0003_student_students_st_deleted_257675_idx'),
    ]

    operations = [
        migrations.RemoveIndex(
            model_name='student',
            name='students_st_school__4d90f3_idx',
        ),
        migrations.RemoveIndex(
            model_name='student',
            name='students_st_deleted_257675_idx',
        ),
        migrations.AddIndex(
            model_name='student',
            index=models.Index(fields=['school_class_id', 'deleted_at'], name='student_class_active_idx'),
        ),
        migrations.AddIndex(
            model_name='student',
            index=models.Index(fields=['deleted_at', 'session'], name='student_session_active_idx'),
        ),
    ]
