# Generated by Django 6.0.6 on 2026-07-24 01:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0006_program'),
        ('students', '0007_student_program'),
    ]

    operations = [
        migrations.AddConstraint(
            model_name='student',
            constraint=models.UniqueConstraint(condition=models.Q(('roll__gt', '')), fields=('roll', 'school_class'), name='unique_roll_per_class'),
        ),
    ]
