# Generated by Django 6.0.6 on 2026-06-10 19:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0003_alter_category_unique_together_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='auditlog',
            name='user_name',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
