# Generated by Django 6.0.6 on 2026-06-11 10:51

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0004_add_auditlog_user_name'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='academicyear',
            options={'ordering': ['-start_date'], 'verbose_name': 'academic year', 'verbose_name_plural': 'academic years'},
        ),
        migrations.AlterModelOptions(
            name='auditlog',
            options={'ordering': ['-created_at'], 'verbose_name': 'audit log', 'verbose_name_plural': 'audit logs'},
        ),
        migrations.AlterModelOptions(
            name='category',
            options={'ordering': ['type', 'name'], 'verbose_name': 'category', 'verbose_name_plural': 'categories'},
        ),
        migrations.AlterModelOptions(
            name='schoolclass',
            options={'ordering': ['order', 'name'], 'verbose_name': 'school class', 'verbose_name_plural': 'school classes'},
        ),
        migrations.AlterModelOptions(
            name='schoolsetting',
            options={'verbose_name': 'school setting', 'verbose_name_plural': 'school settings'},
        ),
        migrations.AlterModelOptions(
            name='subject',
            options={'ordering': ['order', 'name'], 'verbose_name': 'subject', 'verbose_name_plural': 'subjects'},
        ),
    ]
