# Generated by Django 6.0.6 on 2026-07-20 19:51

import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0005_alter_academicyear_options_alter_auditlog_options_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Program',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=255, unique=True)),
                ('active', models.BooleanField(default=True)),
            ],
            options={
                'verbose_name': 'program',
                'verbose_name_plural': 'programs',
                'ordering': ['name'],
            },
        ),
    ]
