# Generated by Django 6.0.6 on 2026-06-04 10:36

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('core', '0001_initial'),
        ('students', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='PeriodClose',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('fiscal_year', models.IntegerField(unique=True)),
                ('closed_at', models.DateTimeField(auto_now_add=True)),
                ('closed_by', models.CharField(blank=True, max_length=100, null=True)),
                ('notes', models.TextField(blank=True, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='FeeSchedule',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('category', models.CharField(max_length=100)),
                ('amount', models.DecimalField(decimal_places=2, max_digits=12)),
                ('frequency', models.CharField(choices=[('MONTHLY', 'Monthly'), ('YEARLY', 'Yearly'), ('ONE_TIME', 'One Time')], default='MONTHLY', max_length=20)),
                ('applicability', models.CharField(choices=[('AUTO', 'Auto'), ('ASSIGNED_ONLY', 'Assigned Only')], default='AUTO', max_length=20)),
                ('effective_from', models.DateField(blank=True, null=True)),
                ('effective_to', models.DateField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('academic_year', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='fee_schedules', to='core.academicyear')),
                ('school_class', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='fee_schedules', to='core.schoolclass')),
            ],
        ),
        migrations.CreateModel(
            name='FeeWaiver',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('type', models.CharField(choices=[('CUSTOM_AMOUNT', 'Custom Amount')], default='CUSTOM_AMOUNT', max_length=20)),
                ('value', models.DecimalField(decimal_places=2, max_digits=12)),
                ('reason', models.TextField(blank=True, null=True)),
                ('approved_by', models.CharField(blank=True, max_length=100, null=True)),
                ('active', models.BooleanField(default=True)),
                ('starts_at', models.DateField(blank=True, null=True)),
                ('ends_at', models.DateField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('fee_schedule', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='waivers', to='finance.feeschedule')),
                ('student', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='fee_waivers', to='students.student')),
            ],
        ),
        migrations.CreateModel(
            name='OpeningBalance',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('fiscal_year', models.IntegerField()),
                ('account', models.CharField(max_length=100)),
                ('amount', models.DecimalField(decimal_places=2, default=0, max_digits=12)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('updated_by', models.CharField(blank=True, max_length=100, null=True)),
            ],
            options={
                'unique_together': {('fiscal_year', 'account')},
            },
        ),
        migrations.CreateModel(
            name='OpeningBalanceHistory',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('fiscal_year', models.IntegerField()),
                ('account', models.CharField(max_length=100)),
                ('old_amount', models.DecimalField(decimal_places=2, default=0, max_digits=12)),
                ('new_amount', models.DecimalField(decimal_places=2, default=0, max_digits=12)),
                ('changed_by', models.CharField(blank=True, max_length=100, null=True)),
                ('changed_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'indexes': [models.Index(fields=['fiscal_year', 'account'], name='finance_ope_fiscal__d289b8_idx')],
            },
        ),
        migrations.CreateModel(
            name='ReceiptCounter',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('fiscal_year', models.IntegerField()),
                ('receipt_type', models.CharField(max_length=20)),
                ('next_sequence', models.IntegerField(default=1)),
            ],
            options={
                'unique_together': {('fiscal_year', 'receipt_type')},
            },
        ),
        migrations.CreateModel(
            name='Reconciliation',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('account', models.CharField(max_length=100)),
                ('statement_date', models.DateTimeField()),
                ('closing_balance', models.DecimalField(decimal_places=2, max_digits=12)),
                ('system_balance', models.DecimalField(decimal_places=2, default=0, max_digits=12)),
                ('difference', models.DecimalField(decimal_places=2, default=0, max_digits=12)),
                ('status', models.CharField(choices=[('pending', 'Pending'), ('matched', 'Matched'), ('difference', 'Difference')], default='pending', max_length=20)),
                ('notes', models.TextField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('created_by', models.CharField(blank=True, max_length=100, null=True)),
            ],
            options={
                'indexes': [models.Index(fields=['account'], name='finance_rec_account_ce4995_idx'), models.Index(fields=['created_at'], name='finance_rec_created_410d6b_idx')],
            },
        ),
        migrations.CreateModel(
            name='StudentFeeAssignment',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('active', models.BooleanField(default=True)),
                ('starts_at', models.DateField(blank=True, null=True)),
                ('ends_at', models.DateField(blank=True, null=True)),
                ('note', models.TextField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('fee_schedule', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='student_assignments', to='finance.feeschedule')),
                ('student', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='student_fee_assignments', to='students.student')),
            ],
        ),
        migrations.CreateModel(
            name='Transaction',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('transaction_date', models.DateTimeField()),
                ('transaction_type', models.CharField(choices=[('INCOME', 'Income'), ('EXPENSE', 'Expense'), ('INTERNAL_TRANSFER', 'Internal Transfer')], max_length=50)),
                ('source_account', models.CharField(blank=True, max_length=100, null=True)),
                ('destination_account', models.CharField(blank=True, max_length=100, null=True)),
                ('amount', models.DecimalField(decimal_places=2, max_digits=12)),
                ('category', models.CharField(blank=True, max_length=100, null=True)),
                ('description', models.TextField(blank=True, null=True)),
                ('class_name', models.CharField(blank=True, max_length=100, null=True)),
                ('affects_income_ledger', models.BooleanField(default=False)),
                ('affects_expense_ledger', models.BooleanField(default=False)),
                ('created_by', models.CharField(blank=True, max_length=100, null=True)),
                ('approved_by', models.CharField(blank=True, max_length=100, null=True)),
                ('reference_id', models.CharField(blank=True, max_length=255, null=True, unique=True)),
                ('fee_month', models.CharField(blank=True, max_length=20, null=True)),
                ('fiscal_year', models.IntegerField(blank=True, null=True)),
                ('receipt_sequence', models.IntegerField(blank=True, null=True)),
                ('is_cancelled', models.BooleanField(default=False)),
                ('cancelled_at', models.DateTimeField(blank=True, null=True)),
                ('cancelled_by', models.CharField(blank=True, max_length=100, null=True)),
                ('cancel_reason', models.TextField(blank=True, null=True)),
                ('reversal_of_id', models.UUIDField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('student', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='transactions', to='students.student')),
            ],
        ),
        migrations.CreateModel(
            name='PaymentAllocation',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('period', models.CharField(blank=True, max_length=20, null=True)),
                ('amount', models.DecimalField(decimal_places=2, max_digits=12)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('fee_schedule', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='payment_allocations', to='finance.feeschedule')),
                ('student', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='payment_allocations', to='students.student')),
                ('transaction', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='payment_allocations', to='finance.transaction')),
            ],
        ),
        migrations.AddIndex(
            model_name='feeschedule',
            index=models.Index(fields=['academic_year', 'school_class', 'category'], name='finance_fee_academi_16d9ff_idx'),
        ),
        migrations.AlterUniqueTogether(
            name='feeschedule',
            unique_together={('academic_year', 'school_class', 'category', 'frequency')},
        ),
        migrations.AddIndex(
            model_name='feewaiver',
            index=models.Index(fields=['student'], name='finance_fee_student_9dd6de_idx'),
        ),
        migrations.AddIndex(
            model_name='feewaiver',
            index=models.Index(fields=['fee_schedule'], name='finance_fee_fee_sch_633846_idx'),
        ),
        migrations.AlterUniqueTogether(
            name='feewaiver',
            unique_together={('student', 'fee_schedule')},
        ),
        migrations.AddIndex(
            model_name='studentfeeassignment',
            index=models.Index(fields=['student'], name='finance_stu_student_1171ec_idx'),
        ),
        migrations.AddIndex(
            model_name='studentfeeassignment',
            index=models.Index(fields=['fee_schedule'], name='finance_stu_fee_sch_995361_idx'),
        ),
        migrations.AddIndex(
            model_name='studentfeeassignment',
            index=models.Index(fields=['student', 'fee_schedule'], name='finance_stu_student_9cf2fa_idx'),
        ),
        migrations.AddIndex(
            model_name='transaction',
            index=models.Index(fields=['transaction_date'], name='finance_tra_transac_0cc58e_idx'),
        ),
        migrations.AddIndex(
            model_name='transaction',
            index=models.Index(fields=['transaction_type'], name='finance_tra_transac_2a23c2_idx'),
        ),
        migrations.AddIndex(
            model_name='transaction',
            index=models.Index(fields=['student'], name='finance_tra_student_38322f_idx'),
        ),
        migrations.AddIndex(
            model_name='transaction',
            index=models.Index(fields=['class_name'], name='finance_tra_class_n_d96a70_idx'),
        ),
        migrations.AddIndex(
            model_name='transaction',
            index=models.Index(fields=['category'], name='finance_tra_categor_afb10f_idx'),
        ),
        migrations.AddIndex(
            model_name='transaction',
            index=models.Index(fields=['student', 'category'], name='finance_tra_student_764438_idx'),
        ),
        migrations.AddIndex(
            model_name='transaction',
            index=models.Index(fields=['class_name', 'category'], name='finance_tra_class_n_243748_idx'),
        ),
        migrations.AddIndex(
            model_name='transaction',
            index=models.Index(fields=['transaction_type', 'affects_income_ledger'], name='finance_tra_transac_840b41_idx'),
        ),
        migrations.AddIndex(
            model_name='transaction',
            index=models.Index(fields=['reversal_of_id'], name='finance_tra_reversa_83ed13_idx'),
        ),
        migrations.AddIndex(
            model_name='transaction',
            index=models.Index(fields=['fiscal_year'], name='finance_tra_fiscal__6b4c0f_idx'),
        ),
        migrations.AddIndex(
            model_name='paymentallocation',
            index=models.Index(fields=['transaction'], name='finance_pay_transac_2ab2b1_idx'),
        ),
        migrations.AddIndex(
            model_name='paymentallocation',
            index=models.Index(fields=['fee_schedule'], name='finance_pay_fee_sch_086134_idx'),
        ),
        migrations.AddIndex(
            model_name='paymentallocation',
            index=models.Index(fields=['student', 'period'], name='finance_pay_student_4f99cb_idx'),
        ),
    ]
