# Generated by Django 6.0.6 on 2026-06-04 14:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
        ('finance', '0001_initial'),
    ]

    operations = [
        migrations.AddIndex(
            model_name='feeschedule',
            index=models.Index(fields=['academic_year'], name='finance_fee_academi_3f502f_idx'),
        ),
    ]
