# Generated by Django 6.0.6 on 2026-06-05 04:37

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_alter_subject_id'),
        ('finance', '0003_transaction_date_to_datefield'),
        ('students', '0002_remove_student_photo_alter_student_student_id'),
    ]

    operations = [
        migrations.CreateModel(
            name='AccountBalance',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('fiscal_year', models.IntegerField()),
                ('month', models.IntegerField()),
                ('opening_balance', models.DecimalField(decimal_places=2, default=0, max_digits=14)),
                ('total_debits', models.DecimalField(decimal_places=2, default=0, max_digits=14)),
                ('total_credits', models.DecimalField(decimal_places=2, default=0, max_digits=14)),
                ('closing_balance', models.DecimalField(decimal_places=2, default=0, max_digits=14)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.CreateModel(
            name='BankAccount',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=100, unique=True)),
                ('display_name', models.CharField(max_length=255)),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.AlterModelOptions(
            name='transaction',
            options={},
        ),
        migrations.RemoveIndex(
            model_name='feeschedule',
            name='finance_fee_academi_3f502f_idx',
        ),
        migrations.RemoveIndex(
            model_name='transaction',
            name='finance_tra_transac_0cc58e_idx',
        ),
        migrations.RemoveIndex(
            model_name='transaction',
            name='finance_tra_transac_2a23c2_idx',
        ),
        migrations.RemoveIndex(
            model_name='transaction',
            name='finance_tra_student_38322f_idx',
        ),
        migrations.RemoveIndex(
            model_name='transaction',
            name='finance_tra_class_n_d96a70_idx',
        ),
        migrations.RemoveIndex(
            model_name='transaction',
            name='finance_tra_categor_afb10f_idx',
        ),
        migrations.RemoveIndex(
            model_name='transaction',
            name='finance_tra_fiscal__6b4c0f_idx',
        ),
        migrations.AlterUniqueTogether(
            name='feeschedule',
            unique_together=set(),
        ),
        migrations.AddIndex(
            model_name='transaction',
            index=models.Index(fields=['fiscal_year', 'transaction_type', 'category'], name='finance_tra_fiscal__df3f7a_idx'),
        ),
        migrations.AddIndex(
            model_name='transaction',
            index=models.Index(fields=['student', 'transaction_date'], name='finance_tra_student_77b47b_idx'),
        ),
        migrations.AddIndex(
            model_name='transaction',
            index=models.Index(fields=['transaction_date', 'source_account', 'destination_account'], name='finance_tra_transac_dd6ada_idx'),
        ),
        migrations.AddConstraint(
            model_name='feeschedule',
            constraint=models.UniqueConstraint(fields=('academic_year', 'school_class', 'category', 'frequency'), name='unique_fee_schedule_per_class'),
        ),
        migrations.AddConstraint(
            model_name='feeschedule',
            constraint=models.UniqueConstraint(condition=models.Q(('school_class__isnull', True)), fields=('academic_year', 'category', 'frequency'), name='unique_fee_schedule_global'),
        ),
        migrations.AddField(
            model_name='accountbalance',
            name='account',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='account_balances', to='finance.bankaccount'),
        ),
        migrations.AddIndex(
            model_name='accountbalance',
            index=models.Index(fields=['account', 'fiscal_year', 'month'], name='finance_acc_account_cda07a_idx'),
        ),
        migrations.AlterUniqueTogether(
            name='accountbalance',
            unique_together={('account', 'fiscal_year', 'month')},
        ),
    ]
