# Generated by Django 6.0.6 on 2026-06-05 17:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('finance', '0006_fix_index_names_for_fk'),
        ('students', '0002_remove_student_photo_alter_student_student_id'),
    ]

    operations = [
        migrations.AddIndex(
            model_name='transaction',
            index=models.Index(fields=['is_cancelled', 'transaction_date'], name='finance_tra_is_canc_3aa585_idx'),
        ),
        migrations.AddIndex(
            model_name='transaction',
            index=models.Index(fields=['fee_month', 'fiscal_year'], name='finance_tra_fee_mon_fffbd3_idx'),
        ),
        migrations.AddIndex(
            model_name='transaction',
            index=models.Index(fields=['transaction_date', 'transaction_type'], name='finance_tra_transac_e148a1_idx'),
        ),
    ]
