# Generated by Django 6.0.6 on 2026-06-06 02:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('finance', '0008_cleanup_indexes_and_constraints'),
    ]

    operations = [
        migrations.AddField(
            model_name='transaction',
            name='token_number',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
