# Generated by Django 6.0.6 on 2026-06-07 14:01

from django.db import migrations, models


def convert_dates_to_months(apps, schema_editor):
    """Convert existing date values (YYYY-MM-DD) to month strings (YYYY-MM)."""
    StudentFeeAssignment = apps.get_model('finance', 'StudentFeeAssignment')
    for assignment in StudentFeeAssignment.objects.all():
        changed = False
        if assignment.starts_at and '-' in assignment.starts_at and len(assignment.starts_at) > 7:
            assignment.starts_at = assignment.starts_at[:7]
            changed = True
        if assignment.ends_at and '-' in assignment.ends_at and len(assignment.ends_at) > 7:
            assignment.ends_at = assignment.ends_at[:7]
            changed = True
        if changed:
            assignment.save(update_fields=['starts_at', 'ends_at'])


class Migration(migrations.Migration):

    dependencies = [
        ('finance', '0009_add_token_number'),
    ]

    operations = [
        migrations.RunPython(convert_dates_to_months, migrations.RunPython.noop),
        migrations.AlterField(
            model_name='studentfeeassignment',
            name='ends_at',
            field=models.CharField(blank=True, help_text='Month string YYYY-MM', max_length=7, null=True),
        ),
        migrations.AlterField(
            model_name='studentfeeassignment',
            name='starts_at',
            field=models.CharField(blank=True, help_text='Month string YYYY-MM', max_length=7, null=True),
        ),
    ]
