# Generated by Django 6.0.6 on 2026-06-07 17:18

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('finance', '0010_convert_assignment_dates_to_months'),
    ]

    operations = [
        migrations.AddField(
            model_name='transaction',
            name='entry_date',
            field=models.DateField(default=datetime.date.today, help_text='When entered into system'),
        ),
        migrations.AddField(
            model_name='transaction',
            name='updated_at',
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AddField(
            model_name='transaction',
            name='updated_by',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
