# Generated by Django 6.0.6 on 2026-06-11 10:51

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('finance', '0011_add_entry_date_and_updated_fields'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='accountbalance',
            options={'verbose_name': 'account balance', 'verbose_name_plural': 'account balances'},
        ),
        migrations.AlterModelOptions(
            name='bankaccount',
            options={'verbose_name': 'bank account', 'verbose_name_plural': 'bank accounts'},
        ),
        migrations.AlterModelOptions(
            name='feeschedule',
            options={'verbose_name': 'fee schedule', 'verbose_name_plural': 'fee schedules'},
        ),
        migrations.AlterModelOptions(
            name='feewaiver',
            options={'verbose_name': 'fee waiver', 'verbose_name_plural': 'fee waivers'},
        ),
        migrations.AlterModelOptions(
            name='openingbalance',
            options={'verbose_name': 'opening balance', 'verbose_name_plural': 'opening balances'},
        ),
        migrations.AlterModelOptions(
            name='openingbalancehistory',
            options={'verbose_name': 'opening balance history', 'verbose_name_plural': 'opening balance histories'},
        ),
        migrations.AlterModelOptions(
            name='paymentallocation',
            options={'verbose_name': 'payment allocation', 'verbose_name_plural': 'payment allocations'},
        ),
        migrations.AlterModelOptions(
            name='periodclose',
            options={'verbose_name': 'period close', 'verbose_name_plural': 'period closes'},
        ),
        migrations.AlterModelOptions(
            name='receiptcounter',
            options={'verbose_name': 'receipt counter', 'verbose_name_plural': 'receipt counters'},
        ),
        migrations.AlterModelOptions(
            name='reconciliation',
            options={'verbose_name': 'reconciliation', 'verbose_name_plural': 'reconciliations'},
        ),
        migrations.AlterModelOptions(
            name='studentfeeassignment',
            options={'verbose_name': 'student fee assignment', 'verbose_name_plural': 'student fee assignments'},
        ),
        migrations.AlterModelOptions(
            name='transaction',
            options={'verbose_name': 'transaction', 'verbose_name_plural': 'transactions'},
        ),
    ]
