# Generated by Django 6.0.6 on 2026-06-14 18:49

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('finance', '0012_alter_accountbalance_options_and_more'),
        ('students', '0006_alter_student_options'),
    ]

    operations = [
        migrations.AlterField(
            model_name='feewaiver',
            name='student',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='fee_waivers', to='students.student'),
        ),
        migrations.AlterField(
            model_name='paymentallocation',
            name='student',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='payment_allocations', to='students.student'),
        ),
        migrations.AlterField(
            model_name='studentfeeassignment',
            name='student',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='student_fee_assignments', to='students.student'),
        ),
        migrations.AlterField(
            model_name='transaction',
            name='student',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='transactions', to='students.student'),
        ),
    ]
