# Generated by Django 6.0.6 on 2026-06-14 19:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('finance', '0013_alter_feewaiver_student_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='feewaiver',
            name='approval_status',
            field=models.CharField(choices=[('pending', 'Pending'), ('approved', 'Approved'), ('rejected', 'Rejected')], default='pending', max_length=20),
        ),
        migrations.AddField(
            model_name='feewaiver',
            name='approved_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='feewaiver',
            name='type',
            field=models.CharField(choices=[('CUSTOM_AMOUNT', 'Custom Amount'), ('PERCENTAGE', 'Percentage')], default='CUSTOM_AMOUNT', max_length=20),
        ),
    ]
