# Generated by Django 6.0.6 on 2026-06-15 00:44

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('finance', '0014_feewaiver_approval_status_feewaiver_approved_at_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='accountbalance',
            name='account',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='account_balances', to='finance.bankaccount'),
        ),
        migrations.AlterField(
            model_name='openingbalance',
            name='account',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='opening_balances', to='finance.bankaccount'),
        ),
        migrations.AlterField(
            model_name='openingbalancehistory',
            name='account',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='balance_history', to='finance.bankaccount'),
        ),
        migrations.AlterField(
            model_name='paymentallocation',
            name='transaction',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='payment_allocations', to='finance.transaction'),
        ),
        migrations.AlterField(
            model_name='reconciliation',
            name='account',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='reconciliations', to='finance.bankaccount'),
        ),
    ]
