# Generated by Django 6.0.6 on 2026-06-04 10:36

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Book',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=255)),
                ('publication', models.CharField(blank=True, max_length=255, null=True)),
                ('mrp', models.DecimalField(decimal_places=2, max_digits=12)),
                ('discounted', models.DecimalField(decimal_places=2, max_digits=12)),
                ('sell', models.DecimalField(decimal_places=2, max_digits=12)),
                ('school_class', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='books', to='core.schoolclass')),
            ],
            options={
                'indexes': [models.Index(fields=['school_class'], name='books_book_school__b5545f_idx')],
            },
        ),
    ]
