# Generated by Django 6.0.6 on 2026-06-05 18:08

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('books', '0001_initial'),
    ]

    operations = [
        migrations.RemoveIndex(
            model_name='book',
            name='books_book_school__b5545f_idx',
        ),
    ]
