# Generated by Django 6.0.6 on 2026-06-12 09:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('books', '0003_alter_book_options_alter_book_publication_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='book',
            name='discounted',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=12),
        ),
        migrations.AlterField(
            model_name='book',
            name='mrp',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=12),
        ),
        migrations.AlterField(
            model_name='book',
            name='sell',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=12),
        ),
    ]
