# Generated by Django 6.0.6 on 2026-06-08 16:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('staff', '0003_staff_staff_staff_deleted_3bbb3a_idx'),
    ]

    operations = [
        migrations.AlterField(
            model_name='staff',
            name='contact',
            field=models.CharField(blank=True, default='', max_length=255),
        ),
        migrations.AlterField(
            model_name='staff',
            name='email',
            field=models.EmailField(blank=True, default='', max_length=254),
        ),
        migrations.AlterField(
            model_name='staff',
            name='photo_path',
            field=models.TextField(blank=True, default=''),
        ),
    ]
