# Generated by Django 6.0.6 on 2026-06-08 17:15

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('staff', '0004_alter_staff_contact_alter_staff_email_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='staff',
            options={'verbose_name': 'Staff', 'verbose_name_plural': 'Staff'},
        ),
    ]
