# Generated by Django 6.0.6 on 2026-06-12 17:54

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('core', '0005_alter_academicyear_options_alter_auditlog_options_and_more'),
        ('students', '0006_alter_student_options'),
        ('teachers', '0006_teacher_user_classteacher_teachersubject'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Alert',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('alert_type', models.CharField(choices=[('attendance', 'Attendance'), ('academic', 'Academic'), ('behavior', 'Behavior'), ('parent', 'Parent')], max_length=20)),
                ('title', models.CharField(max_length=255)),
                ('description', models.TextField(blank=True, default='')),
                ('status', models.CharField(choices=[('open', 'Open'), ('pending', 'Pending'), ('resolved', 'Resolved')], default='open', max_length=20)),
                ('severity', models.CharField(choices=[('high', 'High'), ('medium', 'Medium'), ('low', 'Low')], default='medium', max_length=10)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('resolved_at', models.DateTimeField(blank=True, null=True)),
                ('created_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='created_alerts', to=settings.AUTH_USER_MODEL)),
                ('student', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='coordination_alerts', to='students.student')),
            ],
            options={
                'verbose_name': 'Alert',
                'verbose_name_plural': 'Alerts',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='ClassTest',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('test_name', models.CharField(max_length=255)),
                ('test_date', models.DateField()),
                ('total_marks', models.PositiveIntegerField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('created_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='created_class_tests', to=settings.AUTH_USER_MODEL)),
                ('school_class', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='class_tests', to='core.schoolclass')),
                ('subject', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='class_tests', to='core.subject')),
            ],
            options={
                'verbose_name': 'Class Test',
                'verbose_name_plural': 'Class Tests',
                'ordering': ['-test_date'],
            },
        ),
        migrations.CreateModel(
            name='ClassTestMark',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('marks_obtained', models.PositiveIntegerField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('class_test', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='marks', to='coordination.classtest')),
                ('student', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='class_test_marks', to='students.student')),
            ],
            options={
                'verbose_name': 'Class Test Mark',
                'verbose_name_plural': 'Class Test Marks',
            },
        ),
        migrations.CreateModel(
            name='CoordinatorTask',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('title', models.CharField(max_length=255)),
                ('description', models.TextField(blank=True, default='')),
                ('due_date', models.DateField(blank=True, null=True)),
                ('status', models.CharField(choices=[('pending', 'Pending'), ('in_progress', 'In Progress'), ('completed', 'Completed')], default='pending', max_length=20)),
                ('priority', models.CharField(choices=[('high', 'High'), ('medium', 'Medium'), ('low', 'Low')], default='medium', max_length=10)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('completed_at', models.DateTimeField(blank=True, null=True)),
                ('assigned_to', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='assigned_tasks', to=settings.AUTH_USER_MODEL)),
                ('created_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='created_tasks', to=settings.AUTH_USER_MODEL)),
                ('related_alert', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='tasks', to='coordination.alert')),
            ],
            options={
                'verbose_name': 'Coordinator Task',
                'verbose_name_plural': 'Coordinator Tasks',
                'ordering': ['due_date', '-priority'],
            },
        ),
        migrations.CreateModel(
            name='Intervention',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('action_taken', models.TextField()),
                ('followup_date', models.DateField(blank=True, null=True)),
                ('remarks', models.TextField(blank=True, default='')),
                ('status', models.CharField(choices=[('pending', 'Pending'), ('completed', 'Completed'), ('overdue', 'Overdue')], default='pending', max_length=20)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('alert', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='interventions', to='coordination.alert')),
                ('created_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='created_interventions', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Intervention',
                'verbose_name_plural': 'Interventions',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='ParentCommunication',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('communication_type', models.CharField(choices=[('call', 'Call'), ('meeting', 'Meeting'), ('complaint', 'Complaint'), ('follow_up', 'Follow Up')], max_length=20)),
                ('notes', models.TextField()),
                ('followup_date', models.DateField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('created_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='created_communications', to=settings.AUTH_USER_MODEL)),
                ('student', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='parent_communications', to='students.student')),
            ],
            options={
                'verbose_name': 'Parent Communication',
                'verbose_name_plural': 'Parent Communications',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='TeacherWeeklyReport',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('week_start_date', models.DateField()),
                ('attendance_notes', models.TextField(blank=True, default='')),
                ('academics_notes', models.TextField(blank=True, default='')),
                ('behavior_notes', models.TextField(blank=True, default='')),
                ('parent_issues_notes', models.TextField(blank=True, default='')),
                ('recognition_notes', models.TextField(blank=True, default='')),
                ('status', models.CharField(choices=[('draft', 'Draft'), ('submitted', 'Submitted')], default='draft', max_length=20)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('submitted_at', models.DateTimeField(blank=True, null=True)),
                ('class_teacher', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='weekly_reports', to='teachers.classteacher')),
            ],
            options={
                'verbose_name': 'Teacher Weekly Report',
                'verbose_name_plural': 'Teacher Weekly Reports',
                'ordering': ['-week_start_date'],
            },
        ),
        migrations.AddIndex(
            model_name='alert',
            index=models.Index(fields=['status', 'created_at'], name='coordinatio_status_b76b23_idx'),
        ),
        migrations.AddIndex(
            model_name='alert',
            index=models.Index(fields=['alert_type', 'status'], name='coordinatio_alert_t_9e3255_idx'),
        ),
        migrations.AddIndex(
            model_name='alert',
            index=models.Index(fields=['student'], name='coordinatio_student_81e67c_idx'),
        ),
        migrations.AddIndex(
            model_name='classtest',
            index=models.Index(fields=['school_class', 'subject'], name='coordinatio_school__c6c48b_idx'),
        ),
        migrations.AddIndex(
            model_name='classtest',
            index=models.Index(fields=['test_date'], name='coordinatio_test_da_bede25_idx'),
        ),
        migrations.AddConstraint(
            model_name='classtest',
            constraint=models.UniqueConstraint(fields=('school_class', 'subject', 'test_name'), name='unique_test_per_class_subject_name'),
        ),
        migrations.AddConstraint(
            model_name='classtestmark',
            constraint=models.UniqueConstraint(fields=('class_test', 'student'), name='unique_mark_per_student_per_test'),
        ),
        migrations.AddIndex(
            model_name='coordinatortask',
            index=models.Index(fields=['status', 'due_date'], name='coordinatio_status_b3b6f3_idx'),
        ),
        migrations.AddIndex(
            model_name='coordinatortask',
            index=models.Index(fields=['assigned_to'], name='coordinatio_assigne_d8af9a_idx'),
        ),
        migrations.AddIndex(
            model_name='intervention',
            index=models.Index(fields=['status', 'followup_date'], name='coordinatio_status_a9bf83_idx'),
        ),
        migrations.AddIndex(
            model_name='intervention',
            index=models.Index(fields=['alert'], name='coordinatio_alert_i_dad8b2_idx'),
        ),
        migrations.AddIndex(
            model_name='parentcommunication',
            index=models.Index(fields=['student', 'created_at'], name='coordinatio_student_6a0403_idx'),
        ),
        migrations.AddIndex(
            model_name='teacherweeklyreport',
            index=models.Index(fields=['week_start_date'], name='coordinatio_week_st_83c8ca_idx'),
        ),
        migrations.AddIndex(
            model_name='teacherweeklyreport',
            index=models.Index(fields=['status'], name='coordinatio_status_628874_idx'),
        ),
        migrations.AddConstraint(
            model_name='teacherweeklyreport',
            constraint=models.UniqueConstraint(fields=('class_teacher', 'week_start_date'), name='unique_report_per_teacher_week'),
        ),
    ]
