# Generated by Django 6.0.6 on 2026-06-13 01:04

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('coordination', '0001_initial'),
        ('core', '0005_alter_academicyear_options_alter_auditlog_options_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.RemoveConstraint(
            model_name='classtest',
            name='unique_test_per_class_subject_name',
        ),
        migrations.RemoveIndex(
            model_name='classtest',
            name='coordinatio_school__c6c48b_idx',
        ),
        migrations.AddField(
            model_name='classtest',
            name='term',
            field=models.CharField(choices=[('1', '1st Term'), ('2', '2nd Term'), ('3', '3rd Term')], default='1', max_length=10),
        ),
        migrations.AddIndex(
            model_name='classtest',
            index=models.Index(fields=['school_class', 'subject', 'term'], name='coordinatio_school__efdc49_idx'),
        ),
        migrations.AddConstraint(
            model_name='classtest',
            constraint=models.UniqueConstraint(fields=('school_class', 'subject', 'test_name', 'term'), name='unique_test_per_class_subject_name_term'),
        ),
    ]
