# Generated by Django 6.0.6 on 2026-06-06 01:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='role',
            field=models.CharField(choices=[('admin', 'Admin'), ('teacher', 'Teacher'), ('accountant', 'Accountant'), ('super_viewer', 'Super Viewer'), ('viewer', 'Viewer')], default='viewer', max_length=20),
        ),
    ]
