# Generated by Django 6.0.6 on 2026-06-10 18:05

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='DailyQuiz',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('question', models.TextField()),
                ('option_a', models.CharField(max_length=255)),
                ('option_b', models.CharField(max_length=255)),
                ('option_c', models.CharField(max_length=255)),
                ('option_d', models.CharField(max_length=255)),
                ('correct_answer', models.CharField(max_length=1)),
                ('category', models.CharField(default='general', max_length=50)),
                ('quiz_date', models.DateField(unique=True)),
                ('explanation', models.TextField(blank=True, default='')),
                ('generated_by', models.CharField(default='ai', max_length=20)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'verbose_name': 'Daily Quiz',
                'verbose_name_plural': 'Daily Quizzes',
                'ordering': ['-quiz_date'],
            },
        ),
        migrations.CreateModel(
            name='DailyRiddle',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('question', models.TextField()),
                ('hint', models.TextField(blank=True, default='')),
                ('answer', models.CharField(max_length=255)),
                ('riddle_date', models.DateField(unique=True)),
                ('generated_by', models.CharField(default='ai', max_length=20)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'verbose_name': 'Daily Riddle',
                'verbose_name_plural': 'Daily Riddles',
                'ordering': ['-riddle_date'],
            },
        ),
        migrations.CreateModel(
            name='WeeklyChallenge',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('title', models.CharField(max_length=255)),
                ('description', models.TextField()),
                ('challenge_type', models.CharField(choices=[('text', 'Text Response'), ('emoji', 'Emoji Rating')], max_length=20)),
                ('is_active', models.BooleanField(default=True)),
                ('start_date', models.DateField()),
                ('end_date', models.DateField()),
                ('generated_by', models.CharField(default='ai', max_length=20)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'verbose_name': 'Weekly Challenge',
                'verbose_name_plural': 'Weekly Challenges',
                'ordering': ['-start_date'],
            },
        ),
        migrations.CreateModel(
            name='DailyTip',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('tip', models.TextField()),
                ('category', models.CharField(choices=[('classroom', 'Classroom Management'), ('assessment', 'Assessment'), ('engagement', 'Student Engagement'), ('general', 'General')], max_length=50)),
                ('tip_date', models.DateField()),
                ('generated_by', models.CharField(default='ai', max_length=20)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'verbose_name': 'Daily Tip',
                'verbose_name_plural': 'Daily Tips',
                'ordering': ['-tip_date'],
                'unique_together': {('tip_date', 'category')},
            },
        ),
        migrations.CreateModel(
            name='TeacherStreak',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('current_streak', models.IntegerField(default=0)),
                ('longest_streak', models.IntegerField(default=0)),
                ('last_active_date', models.DateField(blank=True, null=True)),
                ('total_days_active', models.IntegerField(default=0)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='teacher_streak', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Teacher Streak',
                'verbose_name_plural': 'Teacher Streaks',
            },
        ),
        migrations.CreateModel(
            name='LessonPlan',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('plan_date', models.DateField()),
                ('class_name', models.CharField(max_length=255)),
                ('subject', models.CharField(max_length=255)),
                ('notes', models.TextField(blank=True, default='')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='lesson_plans', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Lesson Plan',
                'verbose_name_plural': 'Lesson Plans',
                'ordering': ['-plan_date'],
                'unique_together': {('user', 'plan_date', 'class_name', 'subject')},
            },
        ),
        migrations.CreateModel(
            name='MoodCheckin',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('mood', models.IntegerField(choices=[(1, 'Terrible'), (2, 'Bad'), (3, 'Okay'), (4, 'Good'), (5, 'Great')])),
                ('checkin_date', models.DateField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='mood_checkins', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Mood Checkin',
                'verbose_name_plural': 'Mood Checkins',
                'unique_together': {('user', 'checkin_date')},
            },
        ),
        migrations.CreateModel(
            name='QuizResponse',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('selected_answer', models.CharField(max_length=1)),
                ('is_correct', models.BooleanField(default=False)),
                ('answered_at', models.DateTimeField(auto_now_add=True)),
                ('question', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='responses', to='engagement.dailyquiz')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='quiz_responses', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Quiz Response',
                'verbose_name_plural': 'Quiz Responses',
                'unique_together': {('user', 'question')},
            },
        ),
        migrations.CreateModel(
            name='RiddleResponse',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('guess', models.CharField(max_length=255)),
                ('is_correct', models.BooleanField(default=False)),
                ('answered_at', models.DateTimeField(auto_now_add=True)),
                ('riddle', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='responses', to='engagement.dailyriddle')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='riddle_responses', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Riddle Response',
                'verbose_name_plural': 'Riddle Responses',
                'unique_together': {('user', 'riddle')},
            },
        ),
        migrations.CreateModel(
            name='ChallengeResponse',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('text_response', models.TextField(blank=True, default='')),
                ('emoji_response', models.CharField(blank=True, default='', max_length=10)),
                ('responded_at', models.DateTimeField(auto_now_add=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='challenge_responses', to=settings.AUTH_USER_MODEL)),
                ('challenge', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='responses', to='engagement.weeklychallenge')),
            ],
            options={
                'verbose_name': 'Challenge Response',
                'verbose_name_plural': 'Challenge Responses',
                'unique_together': {('user', 'challenge')},
            },
        ),
    ]
