# Generated by Django 6.0.6 on 2026-06-05 18:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('teachers', '0002_remove_teacher_photo'),
    ]

    operations = [
        migrations.AddIndex(
            model_name='teacher',
            index=models.Index(fields=['deleted_at'], name='teachers_te_deleted_f0c1a8_idx'),
        ),
    ]
