# Generated by Django 6.0.6 on 2026-06-10 17:31

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0003_alter_category_unique_together_and_more'),
        ('teachers', '0005_alter_teacher_options'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='teacher',
            name='user',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='teacher_profile', to=settings.AUTH_USER_MODEL),
        ),
        migrations.CreateModel(
            name='ClassTeacher',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('school_class', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='class_teachers', to='core.schoolclass')),
                ('teacher', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='class_teacher_of', to='teachers.teacher')),
            ],
            options={
                'verbose_name': 'Class Teacher',
                'verbose_name_plural': 'Class Teachers',
                'constraints': [models.UniqueConstraint(fields=('teacher', 'school_class'), name='unique_class_teacher')],
            },
        ),
        migrations.CreateModel(
            name='TeacherSubject',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('school_class', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='subject_teachers', to='core.schoolclass')),
                ('subject', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='teacher_assignments', to='core.subject')),
                ('teacher', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='subject_assignments', to='teachers.teacher')),
            ],
            options={
                'verbose_name': 'Teacher Subject',
                'verbose_name_plural': 'Teacher Subjects',
                'constraints': [models.UniqueConstraint(fields=('teacher', 'subject', 'school_class'), name='unique_teacher_subject_class')],
            },
        ),
    ]
