# Generated by Django 6.0.6 on 2026-06-15 22:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('teachers', '0006_teacher_user_classteacher_teachersubject'),
    ]

    operations = [
        migrations.AddField(
            model_name='teacher',
            name='pin',
            field=models.CharField(blank=True, default='', max_length=128),
        ),
    ]
