# Generated by Django 6.0.6 on 2026-07-24 01:59

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0006_program'),
        ('parents', '0004_announcement'),
    ]

    operations = [
        migrations.AddField(
            model_name='announcement',
            name='school_class',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='announcements', to='core.schoolclass'),
        ),
    ]
