# Generated by Django 6.0.6 on 2026-06-30 21:52

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('core', '0005_alter_academicyear_options_alter_auditlog_options_and_more'),
        ('teachers', '0007_add_teacher_pin'),
    ]

    operations = [
        migrations.CreateModel(
            name='Diary',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('section', models.CharField(blank=True, default='', max_length=50)),
                ('date', models.DateField()),
                ('topic', models.CharField(max_length=500)),
                ('activities', models.TextField(blank=True, default='')),
                ('remarks', models.TextField(blank=True, default='')),
                ('attachment', models.TextField(blank=True, default='')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('school_class', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='diaries', to='core.schoolclass')),
                ('subject', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='diaries', to='core.subject')),
                ('teacher', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='diaries', to='teachers.teacher')),
            ],
            options={
                'verbose_name': 'Diary',
                'verbose_name_plural': 'Diaries',
                'ordering': ['-date', '-created_at'],
            },
        ),
        migrations.CreateModel(
            name='Homework',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('section', models.CharField(blank=True, default='', max_length=50)),
                ('date', models.DateField()),
                ('topic', models.CharField(max_length=500)),
                ('description', models.TextField()),
                ('due_date', models.DateField()),
                ('attachment', models.TextField(blank=True, default='')),
                ('published', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('school_class', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='homeworks', to='core.schoolclass')),
                ('subject', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='homeworks', to='core.subject')),
                ('teacher', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='homeworks', to='teachers.teacher')),
            ],
            options={
                'verbose_name': 'Homework',
                'verbose_name_plural': 'Homeworks',
                'ordering': ['-date', '-created_at'],
            },
        ),
        migrations.CreateModel(
            name='RoutineTemplate',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('section', models.CharField(blank=True, default='', max_length=50)),
                ('day', models.CharField(choices=[('sunday', 'Sunday'), ('monday', 'Monday'), ('tuesday', 'Tuesday'), ('wednesday', 'Wednesday'), ('thursday', 'Thursday'), ('friday', 'Friday'), ('saturday', 'Saturday')], max_length=10)),
                ('period_number', models.IntegerField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('school_class', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='routines', to='core.schoolclass')),
                ('subject', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='routines', to='core.subject')),
                ('teacher', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='routines', to='teachers.teacher')),
            ],
            options={
                'verbose_name': 'Routine Template',
                'verbose_name_plural': 'Routine Templates',
                'ordering': ['school_class', 'section', 'day', 'period_number'],
            },
        ),
        migrations.CreateModel(
            name='LessonPlan',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('week_start', models.DateField()),
                ('topic', models.CharField(max_length=500)),
                ('learning_objectives', models.TextField(blank=True, default='')),
                ('activities', models.TextField(blank=True, default='')),
                ('materials', models.TextField(blank=True, default='')),
                ('assessment', models.TextField(blank=True, default='')),
                ('remarks', models.TextField(blank=True, default='')),
                ('completed', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('routine_template', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='lesson_plans', to='academic.routinetemplate')),
            ],
            options={
                'verbose_name': 'Lesson Plan',
                'verbose_name_plural': 'Lesson Plans',
                'ordering': ['week_start', 'routine_template__period_number'],
            },
        ),
        migrations.CreateModel(
            name='ExamRoutine',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('exam_name', models.CharField(max_length=255)),
                ('section', models.CharField(blank=True, default='', max_length=50)),
                ('date', models.DateField()),
                ('start_time', models.TimeField()),
                ('end_time', models.TimeField(blank=True, null=True)),
                ('room', models.CharField(blank=True, default='', max_length=255)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('school_class', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='exam_routines', to='core.schoolclass')),
                ('subject', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='exam_routines', to='core.subject')),
            ],
            options={
                'verbose_name': 'Exam Routine',
                'verbose_name_plural': 'Exam Routines',
                'ordering': ['date', 'start_time'],
                'constraints': [models.UniqueConstraint(fields=('exam_name', 'school_class', 'section', 'subject'), name='unique_exam_subject_per_class')],
            },
        ),
        migrations.AddConstraint(
            model_name='routinetemplate',
            constraint=models.UniqueConstraint(fields=('school_class', 'section', 'day', 'period_number'), name='unique_period_per_day'),
        ),
        migrations.AddConstraint(
            model_name='lessonplan',
            constraint=models.UniqueConstraint(fields=('routine_template', 'week_start'), name='unique_lesson_plan_per_week'),
        ),
    ]
