# Generated by Django 6.0.6 on 2026-06-15 20:33

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('core', '0005_alter_academicyear_options_alter_auditlog_options_and_more'),
        ('students', '0006_alter_student_options'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Holiday',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('date', models.DateField(unique=True)),
                ('name', models.CharField(max_length=255)),
                ('type', models.CharField(choices=[('public', 'Public'), ('school', 'School Event')], default='public', max_length=10)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'ordering': ['-date'],
            },
        ),
        migrations.CreateModel(
            name='AttendanceRecord',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('date', models.DateField()),
                ('term', models.CharField(max_length=255)),
                ('session', models.CharField(max_length=255)),
                ('status', models.CharField(choices=[('present', 'Present'), ('absent', 'Absent'), ('late', 'Late'), ('excused', 'Excused')], max_length=10)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('marked_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
                ('school_class', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.schoolclass')),
                ('student', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='attendance_records', to='students.student')),
            ],
            options={
                'ordering': ['-date'],
                'indexes': [models.Index(fields=['school_class', 'date'], name='attendance__school__55f745_idx'), models.Index(fields=['student', 'date'], name='attendance__student_588cfe_idx'), models.Index(fields=['term', 'session'], name='attendance__term_c8aefd_idx')],
                'constraints': [models.UniqueConstraint(fields=('student', 'date'), name='unique_student_date')],
            },
        ),
    ]
